package com.zhr.sqlitedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAPTER_INFO.
 */
public class ChapterInfo {

    private Long id;
    /** Not-null value. */
    private String comicName;
    /** Not-null value. */
    private String chapterName;
    /** Not-null value. */
    private String comicUrl;

    public ChapterInfo() {
    }

    public ChapterInfo(Long id) {
        this.id = id;
    }

    public ChapterInfo(Long id, String comicName, String chapterName, String comicUrl) {
        this.id = id;
        this.comicName = comicName;
        this.chapterName = chapterName;
        this.comicUrl = comicUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getComicName() {
        return comicName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicName(String comicName) {
        this.comicName = comicName;
    }

    /** Not-null value. */
    public String getChapterName() {
        return chapterName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

    /** Not-null value. */
    public String getComicUrl() {
        return comicUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicUrl(String comicUrl) {
        this.comicUrl = comicUrl;
    }

}
