package com.zhr.sqlitedao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhr.sqlitedao.ComicInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COMIC_INFO.
*/
public class ComicInfoDao extends AbstractDao<ComicInfo, String> {

    public static final String TABLENAME = "COMIC_INFO";

    /**
     * Properties of entity ComicInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ComicName = new Property(0, String.class, "comicName", true, "COMIC_NAME");
        public final static Property ChapterNum = new Property(1, int.class, "chapterNum", false, "CHAPTER_NUM");
        public final static Property ComicAuthor = new Property(2, String.class, "comicAuthor", false, "COMIC_AUTHOR");
        public final static Property ComicIntro = new Property(3, String.class, "comicIntro", false, "COMIC_INTRO");
        public final static Property UpdateDate = new Property(4, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };


    public ComicInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ComicInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COMIC_INFO' (" + //
                "'COMIC_NAME' TEXT PRIMARY KEY NOT NULL ," + // 0: comicName
                "'CHAPTER_NUM' INTEGER NOT NULL ," + // 1: chapterNum
                "'COMIC_AUTHOR' TEXT NOT NULL ," + // 2: comicAuthor
                "'COMIC_INTRO' TEXT NOT NULL ," + // 3: comicIntro
                "'UPDATE_DATE' INTEGER NOT NULL );"); // 4: updateDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COMIC_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ComicInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getComicName());
        stmt.bindLong(2, entity.getChapterNum());
        stmt.bindString(3, entity.getComicAuthor());
        stmt.bindString(4, entity.getComicIntro());
        stmt.bindLong(5, entity.getUpdateDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ComicInfo readEntity(Cursor cursor, int offset) {
        ComicInfo entity = new ComicInfo( //
            cursor.getString(offset + 0), // comicName
            cursor.getInt(offset + 1), // chapterNum
            cursor.getString(offset + 2), // comicAuthor
            cursor.getString(offset + 3), // comicIntro
            new java.util.Date(cursor.getLong(offset + 4)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ComicInfo entity, int offset) {
        entity.setComicName(cursor.getString(offset + 0));
        entity.setChapterNum(cursor.getInt(offset + 1));
        entity.setComicAuthor(cursor.getString(offset + 2));
        entity.setComicIntro(cursor.getString(offset + 3));
        entity.setUpdateDate(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(ComicInfo entity, long rowId) {
        return entity.getComicName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(ComicInfo entity) {
        if(entity != null) {
            return entity.getComicName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
