package com.zhr.sqlitedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMIC_INFO.
 */
public class ComicInfo {

    /** Not-null value. */
    private String comicName;
    private int chapterNum;
    /** Not-null value. */
    private String comicAuthor;
    /** Not-null value. */
    private String comicIntro;
    /** Not-null value. */
    private java.util.Date updateDate;

    public ComicInfo() {
    }

    public ComicInfo(String comicName) {
        this.comicName = comicName;
    }

    public ComicInfo(String comicName, int chapterNum, String comicAuthor, String comicIntro, java.util.Date updateDate) {
        this.comicName = comicName;
        this.chapterNum = chapterNum;
        this.comicAuthor = comicAuthor;
        this.comicIntro = comicIntro;
        this.updateDate = updateDate;
    }

    /** Not-null value. */
    public String getComicName() {
        return comicName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicName(String comicName) {
        this.comicName = comicName;
    }

    public int getChapterNum() {
        return chapterNum;
    }

    public void setChapterNum(int chapterNum) {
        this.chapterNum = chapterNum;
    }

    /** Not-null value. */
    public String getComicAuthor() {
        return comicAuthor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicAuthor(String comicAuthor) {
        this.comicAuthor = comicAuthor;
    }

    /** Not-null value. */
    public String getComicIntro() {
        return comicIntro;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicIntro(String comicIntro) {
        this.comicIntro = comicIntro;
    }

    /** Not-null value. */
    public java.util.Date getUpdateDate() {
        return updateDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateDate(java.util.Date updateDate) {
        this.updateDate = updateDate;
    }

}
