package com.zhr.sqlitedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMIC_DOWNLOAD.
 */
public class ComicDownload {

    /** Not-null value. */
    private String comicName;
    private int chapterNum;
    private int status;
    /** Not-null value. */
    private java.util.Date downloadDate;

    public ComicDownload() {
    }

    public ComicDownload(String comicName) {
        this.comicName = comicName;
    }

    public ComicDownload(String comicName, int chapterNum, int status, java.util.Date downloadDate) {
        this.comicName = comicName;
        this.chapterNum = chapterNum;
        this.status = status;
        this.downloadDate = downloadDate;
    }

    /** Not-null value. */
    public String getComicName() {
        return comicName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComicName(String comicName) {
        this.comicName = comicName;
    }

    public int getChapterNum() {
        return chapterNum;
    }

    public void setChapterNum(int chapterNum) {
        this.chapterNum = chapterNum;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getDownloadDate() {
        return downloadDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDownloadDate(java.util.Date downloadDate) {
        this.downloadDate = downloadDate;
    }

}
