package com.zhr.sqlitedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhr.sqlitedao.News;
import com.zhr.sqlitedao.ComicRecord;
import com.zhr.sqlitedao.ComicDownload;
import com.zhr.sqlitedao.ComicDownloadDetail;
import com.zhr.sqlitedao.ComicInfo;
import com.zhr.sqlitedao.ChapterInfo;

import com.zhr.sqlitedao.NewsDao;
import com.zhr.sqlitedao.ComicRecordDao;
import com.zhr.sqlitedao.ComicDownloadDao;
import com.zhr.sqlitedao.ComicDownloadDetailDao;
import com.zhr.sqlitedao.ComicInfoDao;
import com.zhr.sqlitedao.ChapterInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDaoConfig;
    private final DaoConfig comicRecordDaoConfig;
    private final DaoConfig comicDownloadDaoConfig;
    private final DaoConfig comicDownloadDetailDaoConfig;
    private final DaoConfig comicInfoDaoConfig;
    private final DaoConfig chapterInfoDaoConfig;

    private final NewsDao newsDao;
    private final ComicRecordDao comicRecordDao;
    private final ComicDownloadDao comicDownloadDao;
    private final ComicDownloadDetailDao comicDownloadDetailDao;
    private final ComicInfoDao comicInfoDao;
    private final ChapterInfoDao chapterInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        comicRecordDaoConfig = daoConfigMap.get(ComicRecordDao.class).clone();
        comicRecordDaoConfig.initIdentityScope(type);

        comicDownloadDaoConfig = daoConfigMap.get(ComicDownloadDao.class).clone();
        comicDownloadDaoConfig.initIdentityScope(type);

        comicDownloadDetailDaoConfig = daoConfigMap.get(ComicDownloadDetailDao.class).clone();
        comicDownloadDetailDaoConfig.initIdentityScope(type);

        comicInfoDaoConfig = daoConfigMap.get(ComicInfoDao.class).clone();
        comicInfoDaoConfig.initIdentityScope(type);

        chapterInfoDaoConfig = daoConfigMap.get(ChapterInfoDao.class).clone();
        chapterInfoDaoConfig.initIdentityScope(type);

        newsDao = new NewsDao(newsDaoConfig, this);
        comicRecordDao = new ComicRecordDao(comicRecordDaoConfig, this);
        comicDownloadDao = new ComicDownloadDao(comicDownloadDaoConfig, this);
        comicDownloadDetailDao = new ComicDownloadDetailDao(comicDownloadDetailDaoConfig, this);
        comicInfoDao = new ComicInfoDao(comicInfoDaoConfig, this);
        chapterInfoDao = new ChapterInfoDao(chapterInfoDaoConfig, this);

        registerDao(News.class, newsDao);
        registerDao(ComicRecord.class, comicRecordDao);
        registerDao(ComicDownload.class, comicDownloadDao);
        registerDao(ComicDownloadDetail.class, comicDownloadDetailDao);
        registerDao(ComicInfo.class, comicInfoDao);
        registerDao(ChapterInfo.class, chapterInfoDao);
    }
    
    public void clear() {
        newsDaoConfig.getIdentityScope().clear();
        comicRecordDaoConfig.getIdentityScope().clear();
        comicDownloadDaoConfig.getIdentityScope().clear();
        comicDownloadDetailDaoConfig.getIdentityScope().clear();
        comicInfoDaoConfig.getIdentityScope().clear();
        chapterInfoDaoConfig.getIdentityScope().clear();
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public ComicRecordDao getComicRecordDao() {
        return comicRecordDao;
    }

    public ComicDownloadDao getComicDownloadDao() {
        return comicDownloadDao;
    }

    public ComicDownloadDetailDao getComicDownloadDetailDao() {
        return comicDownloadDetailDao;
    }

    public ComicInfoDao getComicInfoDao() {
        return comicInfoDao;
    }

    public ChapterInfoDao getChapterInfoDao() {
        return chapterInfoDao;
    }

}
