package com.zhr.sqlitedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS.
 */
public class News {

    private Long id;
    /** Not-null value. */
    private String tag;
    /** Not-null value. */
    private java.util.Date time;
    /** Not-null value. */
    private String title;
    private String imagePath;
    /** Not-null value. */
    private String from;
    /** Not-null value. */
    private String contentUrl;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String tag, java.util.Date time, String title, String imagePath, String from, String contentUrl) {
        this.id = id;
        this.tag = tag;
        this.time = time;
        this.title = title;
        this.imagePath = imagePath;
        this.from = from;
        this.contentUrl = contentUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTag() {
        return tag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    /** Not-null value. */
    public String getContentUrl() {
        return contentUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl;
    }

}
